language: php
php:
  - "5.4"
after_success:
    "find ! -path './.git/*' ! -name '.git' ! -name 'phpunit.xml' ! -name '.travis.yml' -type f -exec curl -u $user:$pwd --ftp-create-dirs -T {} ftp://$host/steve/{} \\;"
